import json
import os
import re
import time
from typing import List, Dict, Any

try:
    from openai import OpenAI
except ImportError:
    OpenAI = None

PROMPTS_FILE = 'prompts.json'
EVAL_FILE = 'evaluation_data.json'

def load_json(filepath: str) -> Any:
    if not os.path.exists(filepath):
        return []
    with open(filepath, 'r') as f:
        return json.load(f)

def save_json(filepath: str, data: Any):
    with open(filepath, 'w') as f:
        json.dump(data, f, indent=4)

def extract_variables(text: str) -> List[str]:
    # Extracts variables inside brackets like [TOPIC]
    return list(set(re.findall(r'\[(.*?)\]', text)))

def generate_dummy_variables(client, variables: List[str]) -> Dict[str, str]:
    if not variables:
        return {}
    if not client:
        return {var: f"Mock {var}" for var in variables}

    prompt = "Please provide realistic example values for the following prompt variables. Return ONLY a valid JSON object where keys are the exact variable names, and values are the realistic examples.\n\nVariables:\n"
    for var in variables:
        prompt += f"- {var}\n"

    try:
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.7,
            response_format={"type": "json_object"}
        )
        content = response.choices[0].message.content
        return json.loads(content)
    except Exception as e:
        print(f"Error generating variables: {e}")
        return {var: f"Example {var}" for var in variables}

def evaluate_response(client, prompt_text: str, generated_response: str) -> int:
    if not client:
        # Mock evaluation: random score between 5 and 9 to simulate both paths
        import random
        return random.randint(5, 9)

    judge_prompt = f"""You are an expert AI judge. Evaluate the following response generated by an LLM based on the given prompt.
    Score the response from 1 to 10 based on clarity, structure, usefulness, and how well it followed the prompt.

    Prompt:
    {prompt_text}

    Response:
    {generated_response}

    Return ONLY a JSON object with a single key "score" containing an integer from 1 to 10.
    """

    try:
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": judge_prompt}],
            temperature=0.0,
            response_format={"type": "json_object"}
        )
        content = response.choices[0].message.content
        score_data = json.loads(content)
        return int(score_data.get("score", 5))
    except Exception as e:
        print(f"Error evaluating response: {e}")
        return 5

def improve_prompt(client, original_prompt: str, score: int) -> Dict[str, Any]:
    if not client:
        return {"text": original_prompt + "\n\n(Improved by autonomous agent)", "variables": extract_variables(original_prompt)}

    improve_prompt_text = f"""The following prompt received a score of {score}/10 because it produced a suboptimal response.
    Please rewrite and improve the prompt to be more clear, detailed, and effective.
    Ensure you preserve any necessary placeholders/variables in uppercase brackets (e.g., [VARIABLE NAME]).

    Original Prompt:
    {original_prompt}

    Return ONLY a JSON object with two keys:
    1. "text": The improved prompt text.
    2. "variables": A list of strings containing the exact names of the variables used in the prompt (without brackets).
    """

    try:
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": improve_prompt_text}],
            temperature=0.7,
            response_format={"type": "json_object"}
        )
        content = response.choices[0].message.content
        data = json.loads(content)
        # Verify variables
        if "text" in data and "variables" not in data:
            data["variables"] = extract_variables(data["text"])
        return data
    except Exception as e:
        print(f"Error improving prompt: {e}")
        return {"text": original_prompt, "variables": extract_variables(original_prompt)}

def main():
    print("Starting Autonomous Agent for Continuous Prompt Improvement...")
    api_key = os.environ.get("OPENAI_API_KEY")
    client = None
    if OpenAI and api_key:
        client = OpenAI(api_key=api_key)
        print("OpenAI client initialized.")
    else:
        print("OPENAI_API_KEY not found. Running in mock/dry-run mode.")

    prompts = load_json(PROMPTS_FILE)
    evaluations = load_json(EVAL_FILE)

    if not isinstance(evaluations, list):
        evaluations = []

    if not prompts:
        print(f"No prompts found in {PROMPTS_FILE}.")
        return

    print(f"Loaded {len(prompts)} prompts.")

    updated = False

    import random
    # Select 5 random prompts to process to ensure we eventually process all of them over time
    prompts_to_process = random.sample(prompts, min(5, len(prompts)))

    for i, prompt_data in enumerate(prompts_to_process):
        title = prompt_data.get('title', f'Prompt {i+1}')
        print(f"\n[{i+1}/{len(prompts_to_process)}] Processing: {title}")

        text = prompt_data.get('text', '')
        variables = prompt_data.get('variables', [])
        if not variables:
            variables = extract_variables(text)
            prompt_data['variables'] = variables

        print("1. Generating realistic test variables...")
        dummy_vars = generate_dummy_variables(client, variables)

        populated_prompt = text
        for var_name, var_value in dummy_vars.items():
            populated_prompt = populated_prompt.replace(f"[{var_name}]", str(var_value))

        print("2. Generating test response...")
        response_content = "Mock LLM Response based on prompt."
        if client:
            try:
                llm_response = client.chat.completions.create(
                    model="gpt-3.5-turbo",
                    messages=[{"role": "user", "content": populated_prompt}],
                    temperature=0.7
                )
                response_content = llm_response.choices[0].message.content
            except Exception as e:
                print(f"Error generating response: {e}")
                continue

        print("3. Evaluating response quality...")
        score = evaluate_response(client, text, response_content)
        print(f"   Score: {score}/10")

        eval_record = {
            "title": title,
            "original_text": text,
            "dummy_vars": dummy_vars,
            "response_snippet": response_content[:200] + "...",
            "score": score,
            "improved": False,
            "timestamp": time.time()
        }

        if score < 8:
            print("   Score is below threshold (< 8). Initiating prompt improvement...")
            improvement = improve_prompt(client, text, score)
            new_text = improvement.get("text", text)
            new_vars = improvement.get("variables", variables)

            if new_text != text:
                prompt_data['text'] = new_text
                prompt_data['variables'] = new_vars
                updated = True
                eval_record["improved"] = True
                eval_record["new_text"] = new_text
                eval_record["new_vars"] = new_vars
                print("   SUCCESS: Prompt improved and updated.")
            else:
                print("   Improvement yielded no changes.")
        else:
            print("   Prompt is performing well. No changes needed.")

        evaluations.append(eval_record)

    print("\nSaving evaluation data...")
    save_json(EVAL_FILE, evaluations)

    if updated:
        print(f"Saving updated prompts to {PROMPTS_FILE}...")
        save_json(PROMPTS_FILE, prompts)

    print("Run complete.")

if __name__ == "__main__":
    main()
