import json
import os
import re
import time
import concurrent.futures
from typing import List, Dict, Any

try:
    from openai import OpenAI
except ImportError:
    OpenAI = None

PROMPTS_FILE = 'prompts.json'
EVAL_FILE = 'evaluation_data.json'
MAX_WORKERS = 5
PROMPTS_PER_RUN = 10

def load_json(filepath: str) -> Any:
    if not os.path.exists(filepath):
        return []
    with open(filepath, 'r') as f:
        return json.load(f)

def save_json(filepath: str, data: Any):
    with open(filepath, 'w') as f:
        json.dump(data, f, indent=4)

def extract_variables(text: str) -> List[str]:
    return list(set(re.findall(r'\[(.*?)\]', text)))

def generate_dummy_variables(client, variables: List[str]) -> Dict[str, str]:
    if not variables:
        return {}
    if not client:
        return {var: f"Mock {var}" for var in variables}

    prompt = "Please provide realistic example values for the following prompt variables. Return ONLY a valid JSON object where keys are the exact variable names, and values are the realistic examples.\n\nVariables:\n"
    for var in variables:
        prompt += f"- {var}\n"

    try:
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.7,
            response_format={"type": "json_object"}
        )
        content = response.choices[0].message.content
        return json.loads(content)
    except Exception as e:
        print(f"Error generating variables: {e}")
        return {var: f"Example {var}" for var in variables}

def evaluate_response(client, prompt_text: str, generated_response: str) -> Dict[str, Any]:
    """Evaluates the response and provides a critique if needed."""
    if not client:
        import random
        score = random.randint(5, 9)
        return {
            "score": score,
            "critique": "Mock critique: The response was average." if score < 8 else "Great response."
        }

    judge_prompt = f"""You are an expert AI judge. Evaluate the following response generated by an LLM based on the given prompt.
    Score the response from 1 to 10 based on clarity, structure, usefulness, and how well it followed the prompt.
    Also provide a brief critique explaining the score and what is missing or poorly executed.

    Prompt:
    {prompt_text}

    Response:
    {generated_response}

    Return ONLY a JSON object with two keys:
    1. "score": an integer from 1 to 10.
    2. "critique": a short string explaining the score.
    """

    try:
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": judge_prompt}],
            temperature=0.0,
            response_format={"type": "json_object"}
        )
        content = response.choices[0].message.content
        score_data = json.loads(content)
        return {
            "score": int(score_data.get("score", 5)),
            "critique": score_data.get("critique", "No critique provided.")
        }
    except Exception as e:
        print(f"Error evaluating response: {e}")
        return {"score": 5, "critique": "Error evaluating response."}

def improve_prompt(client, original_prompt: str, evaluation: Dict[str, Any]) -> Dict[str, Any]:
    if not client:
        return {"text": original_prompt + "\n\n(Improved by autonomous agent)", "variables": extract_variables(original_prompt)}

    score = evaluation.get("score")
    critique = evaluation.get("critique")

    improve_prompt_text = f"""The following prompt received a score of {score}/10 because it produced a suboptimal response.
    Critique from Judge: {critique}

    Please rewrite and improve the prompt to be more clear, detailed, and effective to address the critique.
    Ensure you preserve any necessary placeholders/variables in uppercase brackets (e.g., [VARIABLE NAME]).

    Original Prompt:
    {original_prompt}

    Return ONLY a JSON object with two keys:
    1. "text": The improved prompt text.
    2. "variables": A list of strings containing the exact names of the variables used in the prompt (without brackets).
    """

    try:
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": improve_prompt_text}],
            temperature=0.7,
            response_format={"type": "json_object"}
        )
        content = response.choices[0].message.content
        data = json.loads(content)
        # Verify variables
        if "text" in data and "variables" not in data:
            data["variables"] = extract_variables(data["text"])
        return data
    except Exception as e:
        print(f"Error improving prompt: {e}")
        return {"text": original_prompt, "variables": extract_variables(original_prompt)}

def prioritize_prompts(prompts: List[Dict], evaluations: List[Dict]) -> List[Dict]:
    """Prioritizes prompts that have never been evaluated, or have low scores/older evaluations."""
    eval_history = {}
    for ev in evaluations:
        title = ev.get("title")
        if title:
            # Keep the latest evaluation for the title
            if title not in eval_history or ev.get("timestamp", 0) > eval_history[title].get("timestamp", 0):
                eval_history[title] = ev

    def get_priority(prompt):
        title = prompt.get("title", "")
        if title not in eval_history:
            return (0, 0) # Highest priority: never evaluated

        last_eval = eval_history[title]
        score = last_eval.get("score", 10)
        timestamp = last_eval.get("timestamp", 0)
        # Sort by score (lower is higher priority), then by timestamp (older is higher priority)
        return (1, score, timestamp)

    # Sort prompts based on priority
    prioritized = sorted(prompts, key=get_priority)
    return prioritized[:PROMPTS_PER_RUN]

def process_prompt(client, prompt_data: Dict) -> Dict:
    title = prompt_data.get('title', 'Unknown Prompt')
    text = prompt_data.get('text', '')
    variables = prompt_data.get('variables', [])
    if not variables:
        variables = extract_variables(text)
        prompt_data['variables'] = variables

    # print(f"[{title}] 1. Generating realistic test variables...")
    dummy_vars = generate_dummy_variables(client, variables)

    populated_prompt = text
    for var_name, var_value in dummy_vars.items():
        populated_prompt = populated_prompt.replace(f"[{var_name}]", str(var_value))

    # print(f"[{title}] 2. Generating test response...")
    response_content = "Mock LLM Response based on prompt."
    if client:
        try:
            llm_response = client.chat.completions.create(
                model="gpt-3.5-turbo",
                messages=[{"role": "user", "content": populated_prompt}],
                temperature=0.7
            )
            response_content = llm_response.choices[0].message.content
        except Exception as e:
            print(f"[{title}] Error generating response: {e}")
            response_content = f"Error: {e}"

    # print(f"[{title}] 3. Evaluating response quality...")
    evaluation = evaluate_response(client, text, response_content)
    score = evaluation.get("score", 5)

    eval_record = {
        "title": title,
        "original_text": text,
        "dummy_vars": dummy_vars,
        "response_snippet": response_content[:200] + "...",
        "score": score,
        "critique": evaluation.get("critique", ""),
        "improved": False,
        "timestamp": time.time()
    }

    result = {
        "title": title,
        "eval_record": eval_record,
        "updated_prompt": None
    }

    if score < 8:
        # print(f"[{title}] Score {score}/10. Initiating prompt improvement...")
        improvement = improve_prompt(client, text, evaluation)
        new_text = improvement.get("text", text)
        new_vars = improvement.get("variables", variables)

        if new_text != text:
            prompt_data['text'] = new_text
            prompt_data['variables'] = new_vars
            eval_record["improved"] = True
            eval_record["new_text"] = new_text
            eval_record["new_vars"] = new_vars
            result["updated_prompt"] = prompt_data

    return result

def main():
    print("Starting Advanced Autonomous Agent for Continuous Prompt Improvement...")
    api_key = os.environ.get("OPENAI_API_KEY")
    client = None
    if OpenAI and api_key:
        client = OpenAI(api_key=api_key)
        print("OpenAI client initialized.")
    else:
        print("OPENAI_API_KEY not found. Running in mock/dry-run mode.")

    prompts = load_json(PROMPTS_FILE)
    evaluations = load_json(EVAL_FILE)

    if not isinstance(evaluations, list):
        evaluations = []

    if not prompts:
        print(f"No prompts found in {PROMPTS_FILE}.")
        return

    print(f"Loaded {len(prompts)} prompts.")

    prompts_to_process = prioritize_prompts(prompts, evaluations)
    print(f"Selected {len(prompts_to_process)} prompts to process based on priority.")

    updated = False

    # Process prompts concurrently
    with concurrent.futures.ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        future_to_prompt = {executor.submit(process_prompt, client, p): p for p in prompts_to_process}

        for future in concurrent.futures.as_completed(future_to_prompt):
            prompt_data = future_to_prompt[future]
            title = prompt_data.get('title', 'Unknown')
            try:
                result = future.result()
                eval_record = result["eval_record"]
                score = eval_record["score"]
                improved = eval_record["improved"]

                print(f"Completed [{title}]: Score {score}/10 | Improved: {improved}")

                evaluations.append(eval_record)

                if improved and result["updated_prompt"]:
                    # Update the prompt in the main list
                    for idx, p in enumerate(prompts):
                        if p.get('title') == title:
                            prompts[idx] = result["updated_prompt"]
                            updated = True
                            break
            except Exception as exc:
                print(f"[{title}] generated an exception: {exc}")

    print("\nSaving evaluation data...")
    save_json(EVAL_FILE, evaluations)

    if updated:
        print(f"Saving updated prompts to {PROMPTS_FILE}...")
        save_json(PROMPTS_FILE, prompts)

    print("Run complete.")

if __name__ == "__main__":
    main()
